import * as yup from 'yup';

export const schema = yup.object().shape({
  currency: yup.string().required('Currency is required'),
  amount: yup.number().typeError('Amount must be a number').required('Amount is required'),
  purpose: yup.string().required('Purpose is required'),
  gender: yup.string().oneOf(['M', 'F'], 'Gender must be M or F').required('Gender is required'),
  occupation: yup.string().required('Occupation is required'),
  nationality: yup.string().required('Nationality is required'),
  bank_account_number: yup.string().required('Bank account number is required'),
  bank_name: yup.string().required('Bank name is required'),
  first_name: yup.string().required('First name is required'),
  last_name: yup.string().required('Last name is required'),
  date_of_birth: yup.string().required('Date of birth is required'),
  id_type: yup.string().required('ID type is required'),
  id_number: yup.string().required('ID number is required'),
  country_code: yup.string().required('Country code is required'),
  country_of_birth: yup.string().required('Country of birth is required'),
  ext_transaction_id: yup.string().required('Transaction ID is required'),
  sender_passport: yup.string().required('Sender passport is required'),
  receiver_name: yup.string().required('Receiver name is required'),
  receiver_currency: yup.string().required('Receiver currency is required'),
  receiver_id_number: yup.string().required('Receiver ID number is required'),
  receiver_date_of_birth: yup.string().required('Receiver date of birth is required'),
  receiver_passport: yup.string().required('Receiver passport is required'),
  receiver_nationality: yup.string().required('Receiver nationality is required'),
  receiver_address: yup.string().required('Receiver address is required'),
  receiver_phone: yup.string().required('Receiver phone is required'),
});
